#!/usr/bin/env bash
#
# Summary: Install a Elm version using elmenv
#
# Usage: elmenv install [-f] [-kvp] <version>
#        elmenv install [-f] [-kvp] <definition-file>
#        elmenv install -l|--list
#
#   -l/--list          List all available versions
#   -f/--force         Install even if the version appears to be installed already
#   -s/--skip-existing Skip if the version appears to be installed already
#
#   elmenv options:
#
#   -k/--keep          Keep source tree in $ELMENV_BUILD_ROOT after installation
#                      (defaults to $ELMENV_ROOT/sources)
#   -v/--verbose       Verbose mode: print compilation status to stdout
#   -p/--patch         Apply a patch from stdin before building
#
# For detailed information on installing Elm versions with
# elmenv, including a list of environment variables for adjusting
# compilation, see: https://github.com/sonnym/elmenv#usage
#
set -e
[ -n "$ELMENV_DEBUG" ] && set -x

if [ -z "$ELMENV_ROOT" ]; then
  ELMENV_ROOT="${HOME}/.elmenv"
fi

# Add `share/versions/` directory to the list of paths where build definitions are looked up.
shopt -s nullglob
for plugin_path in "$ELMENV_ROOT"/share/versions; do
  ELM_BUILD_DEFINITIONS="${ELM_BUILD_DEFINITIONS}:${plugin_path}"
done
export ELM_BUILD_DEFINITIONS
shopt -u nullglob

parse_options() {
  OPTIONS=()
  ARGUMENTS=()
  local arg option index

  for arg in "$@"; do
    if [ "${arg:0:1}" = "-" ]; then
      if [ "${arg:1:1}" = "-" ]; then
        OPTIONS[${#OPTIONS[*]}]="${arg:2}"
      else
        index=1
        while option="${arg:$index:1}"; do
          [ -n "$option" ] || break
          OPTIONS[${#OPTIONS[*]}]="$option"
          index=$(($index+1))
        done
      fi
    else
      ARGUMENTS[${#ARGUMENTS[*]}]="$arg"
    fi
  done
}

usage() {
  elmenv-help install 2>/dev/null
  [ -z "$1" ] || exit "$1"
}

definitions() {
  local query="$1"
  elmenv --definitions | $(type -p ggrep grep | head -1) -F "$query" || true
}

indent() {
  sed 's/^/  /'
}

unset FORCE
unset SKIP_EXISTING
unset KEEP
unset VERBOSE
unset HAS_PATCH

parse_options "$@"
for option in "${OPTIONS[@]}"; do
  case "$option" in
  "h" | "help" )
    usage 0
    ;;
  "l" | "list" )
    echo "Available versions:"
    definitions | indent
    exit
    ;;
  "f" | "force" )
    FORCE=true
    ;;
  "s" | "skip-existing" )
    SKIP_EXISTING=true
    ;;
  "k" | "keep" )
    [ -n "${ELMENV_BUILD_ROOT}" ] || ELMENV_BUILD_ROOT="${ELMENV_ROOT}/sources"
    ;;
  "v" | "verbose" )
    VERBOSE="-v"
    ;;
  "p" | "patch" )
    HAS_PATCH="-p"
    ;;
  "version" )
    exec elmenv --version
    ;;
  * )
    usage 1 >&2
    ;;
  esac
done

[ "${#ARGUMENTS[@]}" -le 1 ] || usage 1 >&2

unset VERSION_NAME

# The first argument contains the definition to install. If the
# argument is missing, try to install whatever local app-specific
# version is specified by elmenv. Show usage instructions if a local
# version is not specified.
DEFINITION="${ARGUMENTS[0]}"
[ -n "$DEFINITION" ] || DEFINITION="$(elmenv-local 2>/dev/null || true)"
[ -n "$DEFINITION" ] || usage 1 >&2

# Define `before_install` and `after_install` functions that allow
# plugin hooks to register a string of code for execution before or
# after the installation process.
declare -a before_hooks after_hooks

before_install() {
  local hook="$1"
  before_hooks["${#before_hooks[@]}"]="$hook"
}

after_install() {
  local hook="$1"
  after_hooks["${#after_hooks[@]}"]="$hook"
}

OLDIFS="$IFS"
IFS=$'\n' scripts=(`elmenv-hooks install`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do source "$script"; done


# Set VERSION_NAME from $DEFINITION, if it is not already set. Then
# compute the installation prefix.
[ -n "$VERSION_NAME" ] || VERSION_NAME="${DEFINITION##*/}"
PREFIX="${ELMENV_ROOT}/versions/${VERSION_NAME}"

[ -d "${PREFIX}" ] && PREFIX_EXISTS=1

# If the installation prefix exists, prompt for confirmation unless
# the --force option was specified.
if [ -d "${PREFIX}/bin" ]; then
  if [ -z "$FORCE" ] && [ -z "$SKIP_EXISTING" ]; then
    echo "elmenv: $PREFIX already exists" >&2
    read -p "continue with installation? (y/N) "

    case "$REPLY" in
    y* | Y* ) ;;
    * ) exit 1 ;;
    esac
  elif [ -n "$SKIP_EXISTING" ]; then
    # Since we know the ruby version is already installed, and are opting to
    # not force installation of existing versions, we just `exit 0` here to
    # leave things happy
    exit 0
  fi
fi

# If ELMENV_BUILD_ROOT is set, always pass keep options to elmenv.
if [ -n "${ELMENV_BUILD_ROOT}" ]; then
  export ELM_BUILD_BUILD_PATH="${ELMENV_BUILD_ROOT}/${VERSION_NAME}"
  KEEP="-k"
fi

# Set ELM_BUILD_CACHE_PATH to $ELMENV_ROOT/cache, if the directory
# exists and the variable is not already set.
if [ -z "${ELM_BUILD_CACHE_PATH}" ] && [ -d "${ELMENV_ROOT}/cache" ]; then
  export ELM_BUILD_CACHE_PATH="${ELMENV_ROOT}/cache"
fi

# Default ELMENV_VERSION to the globally-specified Elm version. (The
# REE installer requires an existing Elm installation to run. An
# unsatisfied local .ruby-version file can cause the installer to
# fail.)
export ELMENV_VERSION="$(elmenv-global 2>/dev/null || true)"


# Execute `before_install` hooks.
for hook in "${before_hooks[@]}"; do eval "$hook"; done

# Plan cleanup on unsuccessful installation.
cleanup() {
  [ -z "${PREFIX_EXISTS}" ] && rm -rf "$PREFIX"
}

trap cleanup SIGINT

# Invoke `elmenv` and record the exit status in $STATUS.
STATUS=0
echo "$VERSION"
cd elm-platform/installers && runhaskell BuildFromSource.hs "$VERSION_NAME" || STATUS="$?"
cd -

# Execute `after_install` hooks.
for hook in "${after_hooks[@]}"; do eval "$hook"; done

# Run `elmenv-rehash` after a successful installation.
if [ "$STATUS" == "0" ]; then
  elmenv-rehash
else
  cleanup
fi

exit "$STATUS"
