#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export ELMENV_DEBUG=1
  shift
fi

if [ -n "$ELMENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

if enable -f "${0%/*}"/../libexec/elmenv-realpath.dylib realpath 2>/dev/null; then
  abs_dirname() {
    local path="$(realpath "$1")"
    echo "${path%/*}"
  }
else
  if [ -n "$ELMENV_NATIVE_EXT" ]; then
    echo "elmenv: failed to load \`realpath' builtin" >&2
    exit 1
  fi
READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "elmenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}
fi

if [ -z "${ELMENV_ROOT}" ]; then
  ELMENV_ROOT="${HOME}/.elmenv"
else
  ELMENV_ROOT="${ELMENV_ROOT%/}"
fi
export ELMENV_ROOT

if [ -z "${ELMENV_DIR}" ]; then
  ELMENV_DIR="$(pwd)"
else
  cd "$ELMENV_DIR" 2>/dev/null || {
    echo "elmenv: cannot change working directory to \`$ELMENV_DIR'"
    exit 1
  } >&2
  ELMENV_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export ELMENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${ELMENV_ROOT}/plugins/"*/bin; do
  PATH="${plugin_bin}:${PATH}"
done
export PATH="${bin_path}:${PATH}"

ELMENV_HOOK_PATH="${ELMENV_HOOK_PATH}:${ELMENV_ROOT}/elmenv.d"
if [ "${bin_path%/*}" != "$ELMENV_ROOT" ]; then
  # Add elmenv's own `elmenv.d` unless elmenv was cloned to ELMENV_ROOT
  ELMENV_HOOK_PATH="${ELMENV_HOOK_PATH}:${bin_path%/*}/elmenv.d"
fi
ELMENV_HOOK_PATH="${ELMENV_HOOK_PATH}:/usr/local/etc/elmenv.d:/etc/elmenv.d:/usr/lib/elmenv/hooks"
for plugin_hook in "${ELMENV_ROOT}/plugins/"*/etc/elmenv.d; do
  ELMENV_HOOK_PATH="${ELMENV_HOOK_PATH}:${plugin_hook}"
done
export ELMENV_HOOK_PATH

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(elmenv-version)\n$(elmenv-help)" >&2
  ;;
"-v" )
  exec elmenv-version
  ;;
* )
  command_path="$(command -v "elmenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "elmenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
