#!/usr/bin/env bash
# Summary: List all Elm versions that contain the given executable
# Usage: elmenv whence [--path] <command>

set -e
[ -n "$ELMENV_DEBUG" ] && set -x

# Provide elmenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec elmenv-shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  elmenv-versions --bare | while read version; do
    path="$(elmenv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

ELMENV_COMMAND="$1"
if [ -z "$ELMENV_COMMAND" ]; then
  elmenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$ELMENV_COMMAND")"
[ -n "$result" ] && echo "$result"
