#!/usr/bin/env bash
#
# Summary: Uninstall a specific Elm version
#
# Usage: elmenv uninstall [-f|--force] <version>
#
#    -f  Attempt to remove the specified version without prompting
#        for confirmation. If the version does not exist, do not
#        display an error message.
#
# See `elmenv versions` for a complete list of installed versions.
#
set -e

# Provide elmenv completions
if [ "$1" = "--complete" ]; then
  exec elmenv versions --bare
fi

usage() {
  # We can remove the sed fallback once elmenv 0.4.0 is widely available.
  elmenv-help uninstall 2>/dev/null || sed -ne '/^#/!q;s/.//;s/.//;1,4d;p' < "$0"
  [ -z "$1" ] || exit "$1"
}

if [ -z "$ELMENV_ROOT" ]; then
  ELMENV_ROOT="${HOME}/.elmenv"
fi

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  usage 0
fi

unset FORCE
if [ "$1" = "-f" ] || [ "$1" = "--force" ]; then
  FORCE=true
  shift
fi

[ "$#" -eq 1 ] || usage 1 >&2

DEFINITION="$1"
case "$DEFINITION" in
"" | -* )
  usage 1 >&2
  ;;
esac

declare -a before_hooks after_hooks

before_uninstall() {
  local hook="$1"
  before_hooks["${#before_hooks[@]}"]="$hook"
}

after_uninstall() {
  local hook="$1"
  after_hooks["${#after_hooks[@]}"]="$hook"
}

OLDIFS="$IFS"
IFS=$'\n' scripts=(`elmenv-hooks uninstall`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do source "$script"; done


VERSION_NAME="${DEFINITION##*/}"
PREFIX="${ELMENV_ROOT}/versions/${VERSION_NAME}"

if [ -z "$FORCE" ]; then
  if [ ! -d "$PREFIX" ]; then
    echo "elmenv: version \`$VERSION_NAME' not installed" >&2
    exit 1
  fi

  read -p "elmenv: remove $PREFIX? "
  case "$REPLY" in
  y* | Y* ) ;;
  * ) exit 1 ;;
  esac
fi

for hook in "${before_hooks[@]}"; do eval "$hook"; done

if [ -d "$PREFIX" ]; then
  rm -rf "$PREFIX"
  elmenv-rehash
fi

for hook in "${after_hooks[@]}"; do eval "$hook"; done
