#!/usr/bin/env bash
# Summary: Show the current Elm version and its origin
#
# Shows the currently selected Elm version and how it was
# selected. To obtain only the version string, use `elmenv
# version-name'.

set -e
[ -n "$ELMENV_DEBUG" ] && set -x

echo "$(elmenv-version-name) (set by $(elmenv-version-origin))"
