#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific Elm version
#
# Usage: elmenv shell <version>
#        elmenv shell --unset
#
# Sets a shell-specific Elm version by setting the `ELMENV_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a Elm version known to elmenv.
# The special version string `system' will use your default system Elm.
# Run `elmenv versions' for a list of available Elm versions.

set -e
[ -n "$ELMENV_DEBUG" ] && set -x

# Provide elmenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec elmenv-versions --bare
fi

version="$1"
shell="$(basename "${ELMENV_SHELL:-$SHELL}")"

if [ -z "$version" ]; then
  if [ -z "$ELMENV_VERSION" ]; then
    echo "elmenv: no shell-specific version configured" >&2
    exit 1
  else
    echo "echo \"\$ELMENV_VERSION\""
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  case "$shell" in
  fish )
    echo "set -e ELMENV_VERSION"
    ;;
  * )
    echo "unset ELMENV_VERSION"
    ;;
  esac
  exit
fi

# Make sure the specified version is installed.
if elmenv-prefix "$version" >/dev/null; then
  case "$shell" in
  fish )
    echo "setenv ELMENV_VERSION \"${version}\""
    ;;
  * )
    echo "export ELMENV_VERSION=\"${version}\""
    ;;
  esac
else
  echo "false"
  exit 1
fi
